insert into users (username, password, profile_image, location, interests) values ('Heidi Frick', 'dictumst', 'https://placeimg.com/640/480/people', 'Végueta', 'Pyrotechnics');
insert into users (username, password, profile_image, location, interests) values ('Ulrich Brayshay', 'maecenas', 'https://placeimg.com/640/480/people', 'Yanwo', 'MPE');
insert into users (username, password, profile_image, location, interests) values ('Tyler Fawssett', 'a', 'https://placeimg.com/640/480/people', 'Skópelos', 'Job Evaluation');
insert into users (username, password, profile_image, location, interests) values ('Jaynell Coll', 'nunc', 'https://placeimg.com/640/480/people', 'Cirangkong', 'Low Voltage');
insert into users (username, password, profile_image, location, interests) values ('Worth Ramsted', 'eros', 'https://placeimg.com/640/480/people', 'Airmolek', 'Small Business Marketing');
insert into users (username, password, profile_image, location, interests) values ('Mirna Palmar', 'commodo', 'https://placeimg.com/640/480/people', 'Buena Vista', 'Research Ethics');
insert into users (username, password, profile_image, location, interests) values ('Kipp Smallacombe', 'consectetuer', 'https://placeimg.com/640/480/people', 'Guamal', 'Broadcast');
insert into users (username, password, profile_image, location, interests) values ('Evita Dolton', 'ipsum', 'https://placeimg.com/640/480/people', 'Ash Shaykh ‘Uthmān', 'Overhaul');
insert into users (username, password, profile_image, location, interests) values ('Mackenzie Warren', 'ipsum', 'https://placeimg.com/640/480/people', 'Kristiansand S', 'DBE');
insert into users (username, password, profile_image, location, interests) values ('Kathryn Biddlecombe', 'vel', 'https://placeimg.com/640/480/people', 'Vabalninkas', 'Russian');
insert into users (username, password, profile_image, location, interests) values ('Casey Morforth', 'in', 'https://placeimg.com/640/480/people', 'Candon', 'Rhino 3D');
insert into users (username, password, profile_image, location, interests) values ('Debby Povele', 'sit', 'https://placeimg.com/640/480/people', 'Baraba', 'MCMS');
insert into users (username, password, profile_image, location, interests) values ('Margalit McGarrell', 'consectetuer', 'https://placeimg.com/640/480/people', 'Vallecillo', 'NTSC');
insert into users (username, password, profile_image, location, interests) values ('Colly Annett', 'tristique', 'https://placeimg.com/640/480/people', 'Malvinas Argentinas', 'TSM');
insert into users (username, password, profile_image, location, interests) values ('Jorey Teek', 'tincidunt', 'https://placeimg.com/640/480/people', 'Rancabolang', 'Ruby on Rails');
insert into users (username, password, profile_image, location, interests) values ('Shamus Spuner', 'maecenas', 'https://placeimg.com/640/480/people', 'Atlanta', 'Commercial Real Estate');
insert into users (username, password, profile_image, location, interests) values ('Amalle Von Gladbach', 'eu', 'https://placeimg.com/640/480/people', 'Uubulan', 'IAX');
insert into users (username, password, profile_image, location, interests) values ('Valentin Embery', 'ipsum', 'https://placeimg.com/640/480/people', 'Peixing', 'Peer Tutoring');
insert into users (username, password, profile_image, location, interests) values ('Daniel Spelman', 'porttitor', 'https://placeimg.com/640/480/people', 'Zouma', 'GCIH');
insert into users (username, password, profile_image, location, interests) values ('Lorelei Bragg', 'in', 'https://placeimg.com/640/480/people', 'A’ershan', 'Tcsh');
